include_guard(GLOBAL)

set(CPACK_PACKAGE_NAME "Vura")
set(CPACK_PACKAGE_VENDOR "${VURA_COMPANY_NAME}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${VURA_COMMENTS}")
set(CPACK_PACKAGE_HOMEPAGE_URL "${VURA_WEBSITE}")

set(CPACK_PACKAGE_VERSION_MAJOR "${VURA_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${VURA_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${VURA_VERSION_PATCH}")
set(CPACK_PACKAGE_VERSION "${VURA_VERSION_CANONICAL}")

set(CPACK_PACKAGE_INSTALL_DIRECTORY "Vura")
set(CPACK_PACKAGE_FILE_NAME "vura-${VURA_VERSION_CANONICAL}-windows-${CMAKE_SYSTEM_PROCESSOR}")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/data/license.txt")

if(WIN32)
    set(CPACK_GENERATOR "NSIS")

    set(CPACK_NSIS_DISPLAY_NAME "Vura")
    set(CPACK_NSIS_PACKAGE_NAME "Vura")
    set(CPACK_NSIS_CONTACT "https://github.com/Hale-Software/Vura")
    set(CPACK_NSIS_URL_INFO_ABOUT "${VURA_WEBSITE}")
    set(CPACK_NSIS_HELP_LINK "${VURA_WEBSITE}")
    set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)

    set(CPACK_PACKAGE_EXECUTABLES "vura64" "Vura")
    set(CPACK_CREATE_DESKTOP_LINKS "vura64")
    set(CPACK_NSIS_MUI_ICON "${CMAKE_CURRENT_SOURCE_DIR}/assets/icons/vura.ico")
    set(CPACK_NSIS_MUI_UNIICON "${CMAKE_CURRENT_SOURCE_DIR}/assets/icons/vura.ico")
else()
    set(CPACK_GENERATOR "ZIP")
endif()

include(CPack)