target_sources(
        vura PRIVATE
        dialogs/about.cpp
        dialogs/about.h
        dialogs/convertmediadialog.cpp
        dialogs/convertmediadialog.h
        dialogs/logviewer.cpp
        dialogs/logviewer.h
        dialogs/MarkerEditDialog.cpp
        dialogs/MarkerEditDialog.h
        dialogs/missingfiles.cpp
        dialogs/missingfiles.h
        dialogs/permissions.cpp
        dialogs/permissions.h
        dialogs/mediainformation.cpp
        dialogs/mediainformation.h
        dialogs/helpdialog.cpp
        dialogs/helpdialog.h
        dialogs/LogUploadDialog.cpp
        dialogs/LogUploadDialog.h
        dialogs/FeedbackDialog.cpp
        dialogs/FeedbackDialog.h
        dialogs/markerdialog.cpp
        dialogs/markerdialog.h
)
