target_sources(
        vura PRIVATE
        widgets/ContinuePlaybackWidget.cpp
        widgets/ContinuePlaybackWidget.h
        widgets/MainWindow.cpp
        widgets/MainWindow.h
        widgets/PlaylistWidget.cpp
        widgets/PlaylistWidget.h
        widgets/SeekSlider.cpp
        widgets/SeekSlider.h
        widgets/SystemTrayWidget.cpp
        widgets/SystemTrayWidget.h
        widgets/VideoControlWidget.cpp
        widgets/VideoControlWidget.h
        widgets/VideoSliderWidget.cpp
        widgets/VideoSliderWidget.h
        widgets/VuraMainWindow.cpp
        widgets/VuraMainWindow.h
)
