name: Build For Windows

on:
  release:
    types: [published]
  #push:
  #  branches: [ main ]
  #  tags: [ 'v*' ]
  #workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean Version Tag
      id: get_version
      shell: bash
      run: |
        # Extracts '1.2.3' from 'refs/tags/v1.2.3' or 'v1.2.3'
        VERSION=${GITHUB_REF_NAME#v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.1'
        target: 'desktop'
        arch: 'win64_mingw'
        dir: '${{ github.workspace }}/Qt'
        modules: 'qtmultimedia'

    - name: Configure CMake
      shell: pwsh
      run: |
          # Set up environment paths for MinGW and Qt
          $qtPath = "${{ github.workspace }}/Qt/6.8.1/mingw_64"
          $env:PATH = "$qtPath/bin;$env:PATH"
          
          cmake -B build -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="$qtPath" -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      shell: pwsh
      run: |
          cmake --build build --config Release

    - name: Compile Installer with Version
      run: |
        makensis /DVERSION="${{ steps.get_version.outputs.version }}" ./installer.nsi

    - name: Upload Installer to Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: ./vura-${{ steps.get_version.outputs.version }}-windows.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}